      - name: Deploy Files via FTP (Safe Clean)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftp
          port: ${{ secrets.FTP_PORT }}
          local-dir: build
          server-dir: ${{ secrets.DEPLOY_PATH }}
          exclude: |
            api/**
            api-backend/**
            .htaccess
          dangerous-clean-slate: true
